spring:
  datasource:
    url: jdbc:mysql://localhost:3306/idoc?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: passw0rd
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  activiti:
    check-process-definitions: false

logging:
  level.root: info
  #level.com.tianheng: debug
  level.com.tianhengyun.yzch.workflow.mapper: debug
  file:
    path:  d:\activiti_logs\data_service.log